[project]
name = 'Blockchain-Based-Public-Auto-Repair-and-Service-Station-Oversight'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.auto-repair-licensing]
path = 'contracts/auto-repair-licensing.clar'
clarity_version = 2
epoch = 2.5

[contracts.consumer-protection]
path = 'contracts/consumer-protection.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
